Lab 1: Tensor Manipulation


In [1]:
import numpy as np
import torch


In [2]:
t= np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)


[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t : ',t.ndim)#차원?
print('shape of t : ',t.shape)

Rank of t :  1
shape of t :  (7,)


In [4]:
print('t[0] t[1] t[-1]=',t[0],t[1],t[-1])
print('t[2:5 t[4:-1]',t[2:5],t[4:-1])

t[0] t[1] t[-1]= 0.0 1.0 6.0
t[2:5 t[4:-1] [2. 3. 4.] [4. 5.]


2D Array np

In [5]:
t=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print('Rank of t ',t.ndim)
print('Shape of t',t.shape)

Rank of t  2
Shape of t (4, 3)


2D array pytorch

In [7]:
t=torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim()) # 차원
print(t.size()) # 행렬 크기
print(t.shape) #행렬크기
print(t[:, 1]) #2번째 열
print(t[:, 1].size())#2번째 열의 사이즈 shape
print(t[:, :-1])# 

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [9]:
print(t[1,1])

tensor(5.)


In [10]:
print(t[2,:1])

tensor([7.])


In [11]:
print(t[3])

tensor([10., 11., 12.])


In [12]:
print(t[:,1])

tensor([ 2.,  5.,  8., 11.])


Shape, Rank, Axis


In [14]:
t=torch.FloatTensor([[[[1,2,3,4],
                       [5,6,7,8,],
                       [9,10,11,12]],
                      [[13,14,15,16],
                      [17,18,19,20],
                      [21,22,23,24]]
                     ]])

In [15]:
print(t.dim())

4


In [37]:
print(t.size())

torch.Size([2, 2])


Frequently Used Operations in Pytorch

Mul , Matmul

In [21]:
print('----------')
print('Mul vs Matmul')
print('----------')
m1=torch.FloatTensor([[1,2],[3,4]])#2차원 형태의 텐서 
m2=torch.FloatTensor([[1],[2]])

print('shape of Matrix 1: ',m1.shape)
print('shape of matrix 2',m2.shape)
print(m1.matmul(m2))##행렬 곱셈

m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

print('shape of matrix 1',m1.shape)
print('shape of matrix 2',m2.shape)
print(m1*m2)
print(m1.mul(m2))##원소별 곱셈 

----------
Mul vs Matmul
----------
shape of Matrix 1:  torch.Size([2, 2])
shape of matrix 2 torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shape of matrix 1 torch.Size([2, 2])
shape of matrix 2 torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Broadcastiog

텐서 연산

텐서는 Numpy의 ndarray와 같이 다양한 수학 연산이 가능하며 GPU를 사용할 시에는 더 빠른 연산이 가능합니다.*이탤릭체 텍스트*
텐서에서의 사칙연산은 같은 타입의 텐서 간 또는 텐서와 파이썬의 스칼라 값 사이에서만 가능합니다.
텐서간이라도 타입이 다르면 연산이 되지 않습니다. FloatTensor와 DoubleTensor간의 사칙연산은 오류가 발생합니다.
스칼라 값을 연산할 때에는 기본적으로 broadcasting이 지원됩니다.

In [22]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [23]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
print(m1+m2)#행렬과 벡터간의 덧셈 -> 브로드캐스팅 발생

tensor([[4., 5.]])


In [24]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


평균


In [26]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [27]:
t=torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)
  

Can only calculate the mean of floating types. Got Long instead.


In [28]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.mean())
print(t.mean(dim=0))# dim=0 첫번째 차원 제거 -> 행렬의 행을 제거 
print(t.mean(dim=1))
print(t.mean(dim=-1))# -> 마지막 차원 제거 

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [30]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [32]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.max())##원소 중 최댓값 리턴 

tensor(4.)


In [34]:
print(t.max(dim=0))##max에 dim인자를 주면 argmax도 함께 리턴된다
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


첫 번째 열에서 3의 인덱스는 1 두 번째 열에서 4의 인덱스는 1이기 때문에 [1,1]이 리턴된다 

In [35]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


max 또는 argmax만 리턴받고 싶다면 다음과 같이 리턴 값에 인덱스를 부여하면 된다.


In [36]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


원소의 수를 유지하면서 텐서의 크기 변경 ★★★

파이토치 텐서에서 뷰는 넘파이의 리쉐이프와 같은 역할


In [38]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]
              ])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [39]:
print(ft.view([-1, 3]))# -1은 첫번째 차원은 사용자가 모르니 파이토치에게 맡기겠다 
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소 개수가 유지되어야 한다. 
size가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

In [40]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


3*1 차원의 텐서를 (3,)의 크기를 가지는 텐서로 변경

In [41]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [42]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


언스퀴즈

In [43]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [45]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [46]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [47]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [48]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절한다.

In [49]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [50]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [51]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [53]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [54]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [55]:
print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [56]:
print(torch.cat([x,y],dim=1))#두 가지 정보를 모두 사용할 때 텐서를 연결한다 

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [57]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [58]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


세 개의 벡터가 순차적으로 쌓여 3x2 텐서가 되었음 

In [59]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


(2,)의 크기에서 unsqueeze(0) -> (1,2)크기의 2차원 텐서로 변경 그리고 cat(concatenate) 

In [60]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


dim=1 2번째 차원이 증가하도록 쌓도록 하는 의미 

In [61]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)


tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [62]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [63]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [64]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [65]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [67]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [68]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
