In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
W = torch.zeros(1, requires_grad=True) #학습을 통해 계속 값이 변경되는 변수임을 의미
print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [8]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [9]:
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [10]:
optimizer = optim.SGD([W, b], lr=0.01) ##SGD는 경사 하강법의 일종 학습 대상인 W와 b가 SGD의 입력이 된다

In [11]:
# gradient를 0으로 초기화 -> 새로운 가중치 편향에 대해 새로운 기울기 구할 수 있음 
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

In [12]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W, b],lr=0.01)


nb_epochs=1999
for epoch in range(nb_epochs+1):

  hypothesis=x_train*W+b
  cost=torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
      print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
          epoch, nb_epochs, W.item(), b.item(), cost.item()
      ))






Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [13]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [14]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [15]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b


    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


행렬 연산으로 이해하기

In [16]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [17]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [18]:
# 가중치와 편향 선언
W = torch.zeros((3, 1), requires_grad=True) ## x_train 5x3 이므로 W의 크기 3x1 행렬 곱 성립
b = torch.zeros(1, requires_grad=True)

In [19]:
hypothesis = x_train.matmul(W) + b

In [20]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # b는 브로드 캐스팅
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [23]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

In [24]:
model=nn.Linear(1,1)

In [25]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [26]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)


In [27]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
  prediction= model(x_train)

  cost=F.mse_loss(prediction,y_train)

  optimizer.zero_grad()

  cost.backward()

  optimizer.step()

  if epoch % 100==0:
    print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/2000 Cost : 13.103541
Epoch  100/2000 Cost : 0.002791
Epoch  200/2000 Cost : 0.001724
Epoch  300/2000 Cost : 0.001066
Epoch  400/2000 Cost : 0.000658
Epoch  500/2000 Cost : 0.000407
Epoch  600/2000 Cost : 0.000251
Epoch  700/2000 Cost : 0.000155
Epoch  800/2000 Cost : 0.000096
Epoch  900/2000 Cost : 0.000059
Epoch 1000/2000 Cost : 0.000037
Epoch 1100/2000 Cost : 0.000023
Epoch 1200/2000 Cost : 0.000014
Epoch 1300/2000 Cost : 0.000009
Epoch 1400/2000 Cost : 0.000005
Epoch 1500/2000 Cost : 0.000003
Epoch 1600/2000 Cost : 0.000002
Epoch 1700/2000 Cost : 0.000001
Epoch 1800/2000 Cost : 0.000001
Epoch 1900/2000 Cost : 0.000000
Epoch 2000/2000 Cost : 0.000000


In [28]:
new_var=torch.FloatTensor([4.0])

pred_y=model(new_var)

print("훈련 후 입력이 4일 때의 예측 값 : ",pred_y)

훈련 후 입력이 4일 때의 예측 값 :  tensor([7.9989], grad_fn=<AddBackward0>)


In [29]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [30]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [31]:
model =nn.Linear(3,1)

In [32]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [33]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [34]:
nb_epochs=2000

for epoch in range(nb_epochs+1):
  prediction=model(x_train)

  cost=F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch %100==0:
    print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/2000 Cost : 42134.707031
Epoch  100/2000 Cost : 5.960053
Epoch  200/2000 Cost : 5.654707
Epoch  300/2000 Cost : 5.365413
Epoch  400/2000 Cost : 5.091429
Epoch  500/2000 Cost : 4.831834
Epoch  600/2000 Cost : 4.585997
Epoch  700/2000 Cost : 4.353045
Epoch  800/2000 Cost : 4.132426
Epoch  900/2000 Cost : 3.923438
Epoch 1000/2000 Cost : 3.725488
Epoch 1100/2000 Cost : 3.537972
Epoch 1200/2000 Cost : 3.360339
Epoch 1300/2000 Cost : 3.192076
Epoch 1400/2000 Cost : 3.032686
Epoch 1500/2000 Cost : 2.881703
Epoch 1600/2000 Cost : 2.738666
Epoch 1700/2000 Cost : 2.603199
Epoch 1800/2000 Cost : 2.474860
Epoch 1900/2000 Cost : 2.353289
Epoch 2000/2000 Cost : 2.238115


In [41]:
new_var=torch.FloatTensor([[73,80,75]])

pred_y=model(new_var)
print('훈련 후 입력이 73, 80 75일 때의 예측 값' ,pred_y)

훈련 후 입력이 73, 80 75일 때의 예측 값 tensor([[153.7184]], grad_fn=<AddmmBackward>)


In [42]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


In [47]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [43]:
class LinearRegreessionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)

In [44]:
model=LinearRegreessionModel()

In [45]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [48]:
nb_epochs=2000

for epoch in range(nb_epochs+1):
  prediction=model(x_train)

  cost=F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch %100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 18.474602
Epoch  100/2000 Cost: 0.136136
Epoch  200/2000 Cost: 0.084124
Epoch  300/2000 Cost: 0.051984
Epoch  400/2000 Cost: 0.032123
Epoch  500/2000 Cost: 0.019850
Epoch  600/2000 Cost: 0.012266
Epoch  700/2000 Cost: 0.007580
Epoch  800/2000 Cost: 0.004684
Epoch  900/2000 Cost: 0.002894
Epoch 1000/2000 Cost: 0.001788
Epoch 1100/2000 Cost: 0.001105
Epoch 1200/2000 Cost: 0.000683
Epoch 1300/2000 Cost: 0.000422
Epoch 1400/2000 Cost: 0.000261
Epoch 1500/2000 Cost: 0.000161
Epoch 1600/2000 Cost: 0.000100
Epoch 1700/2000 Cost: 0.000062
Epoch 1800/2000 Cost: 0.000038
Epoch 1900/2000 Cost: 0.000023
Epoch 2000/2000 Cost: 0.000015


다중회귀 적용


In [49]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [50]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [51]:
model = MultivariateLinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [52]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):


    prediction = model(x_train)
 

    cost = F.mse_loss(prediction, y_train) 

   
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 24821.373047
Epoch  100/2000 Cost: 0.849148
Epoch  200/2000 Cost: 0.825597
Epoch  300/2000 Cost: 0.803225
Epoch  400/2000 Cost: 0.781968
Epoch  500/2000 Cost: 0.761775
Epoch  600/2000 Cost: 0.742599
Epoch  700/2000 Cost: 0.724357
Epoch  800/2000 Cost: 0.707025
Epoch  900/2000 Cost: 0.690548
Epoch 1000/2000 Cost: 0.674883
Epoch 1100/2000 Cost: 0.659985
Epoch 1200/2000 Cost: 0.645810
Epoch 1300/2000 Cost: 0.632342
Epoch 1400/2000 Cost: 0.619514
Epoch 1500/2000 Cost: 0.607307
Epoch 1600/2000 Cost: 0.595680
Epoch 1700/2000 Cost: 0.584620
Epoch 1800/2000 Cost: 0.574083
Epoch 1900/2000 Cost: 0.564048
Epoch 2000/2000 Cost: 0.554477
